INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Abacavir','Comprimido','300 mg',NULL,2.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Abiraterona Acetato','Comprimido','250 mg',NULL,114.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aceite mineral','Emulsión oral','40%',NULL,10.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aceite vitaminado (alimento)','Emulsión oral','Según disponibilidad',NULL,10.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Acetazolamida','Comprimido','250 mg',NULL,1.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Acetil Cisteina','Inyectable','10%',NULL,13.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Suspensión','200 mg/5 ml',NULL,70.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Inyectable','250 mg',NULL,47.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Inyectable','500 mg',NULL,47.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Crema o Pomada oftálmica','3%',NULL,40.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Aciclovir','Crema dérmica ','5%',NULL,16.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Comprimido','800 mg',NULL,7.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Comprimido','200 mg',NULL,2.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aciclovir','Comprimido','400 mg',NULL,1.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido acético (Ácido tricloroacético)','Solución tópica','50%',NULL,74.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido acetil salicílico','Comprimido','100 mg',NULL,0.37,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido acetil salicílico','Comprimido','500 mg',NULL,0.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Alendrónico (Alendronato)','Comprimido','70 mg',NULL,6.65,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido aminocapróico','Inyectable','2g /10 ml',NULL,60.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Ascorbico (Vitamina C)','Inyectable','500 mg/ml (2 ml)',NULL,2.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ácido Ascórbico (Vitamina C)','Solución oral gotas','Según disponibilidad',NULL,20.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Fólico','Comprimido','800 mcg',NULL,0.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido fólico','Comprimido','5 mg',NULL,0.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido nalidíxico','Suspensión','250 mg/5 ml',NULL,29.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido nalidíxico','Suspensión','125 mg/5 ml',NULL,20.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido nalidíxico','Comprimido','500 mg',NULL,1.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Acido p-aminosalicilico','Polvo para solución oral','4 g',NULL,14.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido salicílico','Solución tópica','5%',NULL,27.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Tranexámico','Inyectable','500 mg ',NULL,26.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Tranexámico','Comprimido','500 mg',NULL,10.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ácido Ursodeoxicólico','Cápsula','250 mg',NULL,9.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Valpróico ó Valproato sódico','Jarabe o Solución Oral','200 mg/ml',NULL,99.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Valpróico ó Valproato sódico','Jarabe o Solución oral','250 mg/5 ml',NULL,90.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Valpróico ó Valproato sódico','Jarabe o Solución oral','200 mg/5 ml',NULL,73.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Valpróico ó Valproato sódico','Cápsula o Comprimido','500 mg',NULL,3.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ácido Zoledrónico','Inyectable','4 mg',NULL,486.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Adenosina','Inyectable','6 mg/2 ml',NULL,85.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Agentes con gelatina','Solución parenteral de gran volúmen','Según disponibilidad',NULL,197.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Agua para inyección','Inyectable','5 ml',NULL,1.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Albendazol','Suspensión','200 mg/5 ml',NULL,9.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Albendazol','Comprimido','200 mg',NULL,1.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Albúmina humana','Inyectable','20%',NULL,305.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Alcohol etílico (Etanol)','Solución 1 l','70% a 95%',NULL,22.68,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Alimentos Terapéutico Listo para Uso (ATLU)','Polvo, pasta o Granulado según disponibilidad','Según concentración estándar',NULL,9.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Alopurinol','Comprimido','300 mg',NULL,0.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Alprazolam','Comprimido ranurado','0,5 mg',NULL,0.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amfotericina B','Inyectable','50 mg',NULL,135.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amikacina','Inyectable','500mg /2 ml',NULL,6.17,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aminoácidos','Solución parenteral de gran volumen','10%',NULL,161.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aminofilina','Inyectable','250 mg / 10 ml',NULL,8.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Aminofilina','Comprimido','200 mg',NULL,1.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amiodarona (clorhidrato)','Inyectable','50 mg/ml',NULL,7.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amiodarona (clorhidrato)','Comprimido','200 mg',NULL,2.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amitriptilina','Comprimido ranurado','25 mg',NULL,0.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amlodipina','Comprimido','10 mg',NULL,0.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina','Suspensión','500 mg/5 ml',NULL,12.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina','Inyectable','1 g',NULL,8.08,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina','Comprimido','1 g',NULL,1.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina','Comprimido','500 mg',NULL,0.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina + inhibidor betalactamasa','Suspensión','250 mg + Según disponibilidad',NULL,56.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Amoxicilina + inhibidor betalactamasa','Inyectable','1 g + Según disponibilidad',NULL,24.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina + inhibidor betalactamasa','Comprimido','875 mg + Según disponibilidad',NULL,6.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Amoxicilina + inhibidor betalactamasa','Comprimido','500 mg + Según disponibilidad',NULL,6.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ampicilina','Inyectable','1 g',NULL,5.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Anastrozol','Comprimido','1 mg',NULL,10.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Antigripal (Paracetamol + Antihistamínico + Vasoconstrictor con o sin Cafeína)','Comprimido','Según disponibilidad',NULL,0.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Antitóxina tetánica','Inyectable','Norma PAI según disponibilidad',NULL,50.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aripiprazol','Comprimido','15 mg',NULL,11.34,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Aripiprazol','Comprimido','10 mg',NULL,9.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Artemeter + Lumefantrina','Comprimido','20 mg + 120 mg',NULL,0.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Artesunato','Comprimido','50 mg',NULL,3.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Artesunato ','Inyectable','60 mg',NULL,3.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Artesunato + Mefloquina','Comprimido','100 mg + 220 mg',NULL,2.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Artesunato + Mefloquina','Comprimido','25 mg + 55 mg',NULL,1.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Asparaginasa','Inyectable','10.000 UI',NULL,1626.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atazanavir (sulfato)','Cápsula o Comprimido','300 mg',NULL,7.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atazanavir + Ritonavir','Cápsula o Comprimido','300 mg + 100 mg',NULL,6.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atenolol','Comprimido ranurado','100 mg',NULL,0.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atorvastatina','Comprimido','20 mg',NULL,1.17,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atorvastatina','Comprimido','10 mg',NULL,0.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Atracurio besilato','Inyectable','10 mg/ml',NULL,27.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atropina sulfato','Solución oftálmica','1%',NULL,29.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Atropina sulfato','Inyectable','1 mg/ml',NULL,3.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Azatioprina','Inyectable','20 mg/ml',NULL,214.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Azatioprina','Comprimido','50 mg',NULL,3.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Azitromicina','Suspensión','200 mg/5 ml',NULL,32.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Azitromicina','Comprimido','500 mg',NULL,5.56,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bacitracina + Neomicina sulfato','Crema o Pomada','500 UI + 5 mg/g',NULL,6.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Basiliximab','Polvo para inyectable','20 mg',NULL,16013.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Beclometasona dipropionato','Aerosol','50 mcg/inhalación',NULL,67.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Bedaquilina ','Comprimido ','100 mg',NULL,53.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina benzatínica','Inyectable','2.400.000 UI',NULL,11.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina benzatínica','Inyectable','1.200.000 UI',NULL,6.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina benzatínica','Inyectable','600.000 UI',NULL,5.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina procaínica','Inyectable','800.000 UI',NULL,6.84,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina procaínica','Inyectable','400.000 UI',NULL,5.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina sódica','Inyectable','30.000.000 UI',NULL,35.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bencilpenicilina sódica','Inyectable','1.000.000 UI',NULL,5.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Benznidazol','Comprimido','100 mg',NULL,8.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Benznidazol','Comprimido','50 mg',NULL,4.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Benznidazol','Comprimido','12,5 mg',NULL,1.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Benzoato de bencilo','Solución o Loción','20% o 25%',NULL,9.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Betametasona (fosfato)','Inyectable','4 mg',NULL,6.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Betametasona (valerato)','Crema o Pomada','0,10%',NULL,9.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bevacizumab','Inyectable','25 mg/ml',NULL,5782.74,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bicalutamida','Comprimido','50 mg',NULL,8.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bicarbonato de sodio','Inyectable','8%',NULL,8.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bicarbonato de sodio','Polvo','20 g',NULL,2.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bicarbonato de sodio p/hemodiálisis','Polvo','Frasco por 720 g',NULL,189.42,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Biperideno clorhidrato','Comprimido','4 mg',NULL,4.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Bisacodilo','Comprimido','5 mg',NULL,0.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bisoprolol','Comprimido','5 mg ',NULL,2.96,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bleomicina','Inyectable','15 UI',NULL,304.61,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bortezomib ','Polvo para inyectable','3,5 mg',NULL,13800.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bromocriptina','Comprimido','5 mg',NULL,7.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bromocriptina','Comprimido','2,5 mg',NULL,4.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Budesonida','Aerosol','100 mcg',NULL,129.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bupivacaina clorhidrato','Inyectable','0,50%',NULL,18.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bupivacaina clorhidrato (pesada)','Inyectable','0,50%',NULL,13.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Bupivacaina clorhidrato con Epinefrina sin conservante','Inyectable','0,5% 1:200.000 ',NULL,24.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Busulfano','Comprimido','2 mg',NULL,9.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Butilbromuro de Hioscina (Butilescopolamina)','Solución oral gotas','0,10%',NULL,25.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Butilbromuro de Hioscina (Butilescopolamina)','Inyectable','20 mg/ml',NULL,4.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Butilbromuro de Hioscina (Butilescopolamina)','Comprimido','10 mg',NULL,1.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cabergolina','Comprimido','0,5 mg',NULL,42.64,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cafeína Citrato','Inyectable','20 mg/ml',NULL,120.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Calcio (carbonato o citrato)','Comprimido','500 mg (ión calcio)',NULL,2.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Calcio + Vitamina D','Comprimido o Cápsula','500 mg (ión calcio); Según disponibilidad',NULL,0.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Capecitabine','Comprimido','500 mg',NULL,13.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Capreomicina','Inyectable','1 g',NULL,41.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Carbamazepina','Suspensión o Jarabe','2% (100 mg/5 ml)',NULL,50.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carbamazepina','Comprimido','200 mg',NULL,0.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carbetocina','Inyectable','100 mcg/ml',NULL,261.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carbón medicinal activado','Polvo','Según disponibilidad',NULL,2.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carboplatino','Inyectable','450 mg',NULL,426.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carboplatino','Inyectable','150 mg',NULL,208.34,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carvedilol','Comprimido','12,5 mg',NULL,2.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Carvedilol','Comprimido','6,25 mg',NULL,1.93,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefazolina','Inyectable','1 g',NULL,10.78,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefepima ','Inyectable','1g',NULL,120.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Cefixima','Suspensión','100 mg/5 ml',NULL,38.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefixima','Comprimido o Cápsula','400 mg',NULL,7.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefotaxima','Inyectable','1 g',NULL,7.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefradina','Suspensión','250 mg/5 ml',NULL,32.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cefradina','Cápsula o Comprimido','500 mg',NULL,2.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ceftazidima','Inyectable','1 g',NULL,20.87,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ceftriaxona','Inyectable','1 g',NULL,10.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cetirizina','Jarabe','5 mg/5 ml',NULL,17.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cetirizina','Cápsula o Comprimido ','10 mg',NULL,0.76,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cianocobalamina (Vitamina B12)','Inyectable','1 mg/ml',NULL,4.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ciclofosfamida','Inyectable','1 g',NULL,216.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclofosfamida','Inyectable','500 mg',NULL,164.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclofosfamida','Comprimido','50 mg',NULL,5.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cicloserina','Cápsula','250 mg',NULL,2.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclosporina','Solución oral','100 mg/ml',NULL,1321.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclosporina','Solución oftálmica','0,10%',NULL,221.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclosporina','Cápsula blanda','100 mg',NULL,15.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclosporina','Cápsula blanda','50 mg',NULL,8.95,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciclosporina','Cápsula blanda','25 mg',NULL,6.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciprofloxacina','Solución oftálmica','0,30%',NULL,22.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ciprofloxacina','Inyectable','200 mg',NULL,11.64,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciprofloxacina','Comprimido','250 mg',NULL,1.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciprofloxacina','Comprimido','500 mg',NULL,0.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciproterona (acetato)','Comprimido','50 mg',NULL,6.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciproterona acetato + Estradiol valerato','Comprimido','2 mg + 1 mg',NULL,126.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ciproterona acetato + Estradiol valerato','Comprimido','2 mg + 0,035 mg  ',NULL,59.49,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cisplatino','Inyectable','50 mg',NULL,119.04,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cisplatino','Inyectable','10 mg',NULL,75.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Citarabina','Inyectable','500 mg',NULL,180.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Citarabina','Inyectable','100 mg',NULL,56.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Claritromicina','Suspensión','250 mg/5 ml',NULL,81.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Claritromicina','Comprimido','500 mg',NULL,4.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clindamicina','Suspensión o Jarabe','75 mg/5 ml',NULL,145.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clindamicina','Inyectable','600 mg',NULL,17.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clindamicina','Cápsula o comprimido','300 mg',NULL,10.17,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clobetasol','Solución','0,05%',NULL,56.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clobetasol','Crema o Pomada','0,05%',NULL,13.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clofazimina','Cápsula','100 mg',NULL,10.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clofazimina','Cápsula','50 mg',NULL,5.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clomifeno citrato','Comprimido','50 mg',NULL,3.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Clomipramina','Comprimido','75 mg',NULL,5.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clomipramina (clorhidrato)','Inyectable','25 mg/2 ml',NULL,15.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clonazepam','Solución oral','2,5 mg/ml',NULL,70.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clonazepam','Comprimido ranurado','2 mg',NULL,2.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clopidogrel','Comprimido','75 mg',NULL,3.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloranfenicol','Ungüento oftálmico','1%',NULL,17.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloranfenicol','Solución oftálmica','0,50%',NULL,11.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloranfenicol','Cápsula','500 mg',NULL,1.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloranfenicol succinato sódico','Inyectable','1 g',NULL,4.49,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clorfenamina (Clorfeniramina)','Jarabe','2 mg/5 ml',NULL,8.96,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Clorfenamina (Clorfeniramina)','Inyectable','10 mg/ml',NULL,2.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clorfenamina (Clorfeniramina)','Comprimido','4 mg',NULL,0.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clorhexidina gluconato','Solución','Según disponibilidad',NULL,146.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloroquina fosfato','Comprimido','250 mg (150 mg base)',NULL,0.37,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clorpromazina','Inyectable','12,5 mg/ml',NULL,3.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clorpromazina','Comprimido','100 mg',NULL,1.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloruro de potasio','Solución oral','1,3 mEq/ml',NULL,29.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloruro de potasio','Inyectable','20%',NULL,3.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloruro de sodio','Inyectable','20%',NULL,3.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clotrimazol','Crema vaginal','1%',NULL,10.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Clotrimazol','Crema o Pomada','1%',NULL,7.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Clotrimazol','Óvulo','100 mg',NULL,1.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloxacilina','Inyectable','1 g',NULL,9.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cloxacilina','Inyectable','500 mg',NULL,6.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Codeína','Jarabe','10 mg/5 ml',NULL,17.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Codeína','Comprimido','30 mg',NULL,3.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Colchicina','Comprimido','0,5 mg',NULL,1.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Colecalciferol (Vitamina D3)','Comprimido o Cápsula blanda','0,25 mcg',NULL,2.17,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Colistina','Inyectable','100 mg',NULL,116.98,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complejo  B (B1 + B6 + B12)','Inyectable','Según concentración estándar',NULL,3.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Complejo  B (B1 + B6 + B12)','Comprimido','Según concentración estándar',NULL,0.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complejo de vitaminas y minerales (Uso pediatría) CMV','Polvo para solución oral','Según disponibilidad',NULL,280.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complemento nutricional ','Polvo','Según concentración estándar',NULL,179.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complemento nutricional (Carmelo)','Polvo','Según concentración estándar',NULL,54.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complemento nutricional (Diabético)','Polvo','Según concentración estándar',NULL,57.14,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Complemento nutricional (Nutribebé)','Polvo','Según concentración estándar',NULL,23.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Contraste iodado','Inyectable','Según disponibilidad (100 ml o 200 ml)',NULL,312.26,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Contraste iodado','Inyectable','Según disponibilidad (50 ml)',NULL,304.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Contraste iodado','Inyectable','Según disponibilidad (10 ml)',NULL,195.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Corticoide + anestésico','Crema o Pomada','Según disponibilidad',NULL,42.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Corticoide + anestésico','Supositorio','Según disponibilidad',NULL,3.03,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Corticoide + antiinfeccioso de accion tópica','Ungüento oftálmico','Según disponibilidad',NULL,31.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Corticoide + antiinfeccioso de accion tópica','Solución oftálmica','Según disponibilidad',NULL,22.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Corticotrofina (ACTH)','Inyectable','25 UI o 40 UI',NULL,109.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Suspensión','400 mg + 80 mg/5 ml',NULL,19.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Inyectable','400 mg + 80 mg/5 ml',NULL,17.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Suspensión','200 mg + 40 mg/5 ml',NULL,9.18,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Comprimido','800 mg + 160 mg',NULL,0.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Comprimido','100 mg + 20 mg',NULL,0.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Cotrimoxazol (Sulfametoxazol + Trimetoprima)','Comprimido','400 mg + 80 mg',NULL,0.42,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Dacarbazina','Inyectable','200 mg',NULL,187.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Daclatasvir ','Cápsula o Comprimido','60 mg',NULL,471.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dactinomicina','Inyectable','0,5 mg/ml',NULL,315.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dapsona','Comprimido','100 mg',NULL,6.78,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dapsona','Comprimido','50 mg',NULL,2.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Darunavir','Comprimido','600 mg',NULL,61.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dasatinib','Comprimido','100 mg',NULL,367.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dasatinib','Comprimido','70 mg',NULL,209.73,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dasatinib','Comprimido','50 mg',NULL,196.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dasatinib','Comprimido','20 mg',NULL,41.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Daunorrubicina ','Inyectable','20 mg',NULL,351.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Deferoxamina mesilato','Inyectable','500 mg',NULL,111.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Delamanid ','Comprimido ','100 mg',NULL,106.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Desmopresina acetato','Solución nasal','0,1 mg/ml',NULL,560.19,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexametasona','Ungüento o Pomada oftálmica','0,10%',NULL,37.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexametasona','Solución oftálmica','0,10%',NULL,17.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexametasona','Inyectable','4 mg/ml',NULL,2.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexametasona','Comprimido','4 mg',NULL,0.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexametasona','Comprimido','0,5 mg',NULL,0.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dexmedetomidina ','Inyectable','100 mcg/ml',NULL,150.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Dextrán 70','Solución parenteral de gran volúmen','6%',NULL,67.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dextrometorfano bromhidrato','Jarabe','10 mg/5 ml',NULL,9.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diazepam','Inyectable','10 mg',NULL,6.96,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diazepam','Comprimido ranurado','10 mg',NULL,1.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diazepam','Comprimido ranurado','5 mg',NULL,0.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diclofenaco Sódico','Solución oftálmica','0,10%',NULL,11.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diclofenaco Sódico','Pomada o Gel','1%',NULL,11.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diclofenaco Sódico','Inyectable','75 mg',NULL,1.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Diclofenaco Sódico','Comprimido','50 mg',NULL,0.18,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dicloxacilina sódica','Suspensión','250 mg/5 ml',NULL,15.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Dicloxacilina sódica','Cápsula','500 mg',NULL,1.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Digoxina','Solución oral gotas','0,75 mg/ml',NULL,104.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Digoxina','Inyectable','0,25 mg/ml',NULL,7.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Digoxina','Comprimido ranurado','0,25 mg',NULL,0.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dimenhidrinato','Inyectable','50 mg/ml',NULL,14.91,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dimenhidrinato','Supositorio','50 mg',NULL,4.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dimenhidrinato','Comprimido','50 mg',NULL,0.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dimercaprol (B.A.L.)','Inyectable','100 mg/ml',NULL,758.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dinitrato de isosorbida (Isosorbide dinitrato)','Comprimido sublingual','5 mg',NULL,1.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dobutamina clorhidrato','Inyectable','250 mg',NULL,26.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Docetaxel','Inyectable','40 mg/ml  (2ml)',NULL,543.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Domperidona','Comprimido','10 mg',NULL,0.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dopamina clorhidrato','Inyectable','200 mg',NULL,5.26,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Dorzolamida','Solución oftálmica','2%',NULL,95.14,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Doxiciclina','Cápsula o Comprimido','100 mg',NULL,0.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Doxorrubicina liposomal pegilada','Inyectable','20 mg/ 10 ml',NULL,718.13,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Doxorubicina clorhidrato (Adriamicina clorh.)','Inyectable','50 mg',NULL,174.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Doxorubicina clorhidrato (Adriamicina clorh.)','Inyectable','10 mg',NULL,120.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Droperidol','Inyectable','2,5 mg/ml',NULL,7.61,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Duloxetina ','Cápsula','30 mg',NULL,8.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Edetato sódico de calcio (EDTA)','Inyectable','20%',NULL,122.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Efavirenz','Comprimido','600 mg',NULL,1.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Efavirenz','Comprimido','200 mg',NULL,0.73,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Emulsión de lípidos','Emulsión inyectable','Según disponibilidad',NULL,146.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Enalapril maleato','Comprimido ranurado','10 mg',NULL,0.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Enzalutamida','Cápsula','40 mg',NULL,192.92,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Enzimas pancreáticas (Lipasa, Proteasa y Amilasa en combinación)','Comprimido','Según disponibilidad',NULL,2.18,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Epinefrina (Adrenalina)','Inyectable','1 mg/ml',NULL,6.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ergometrina maleato','Inyectable','0,2 mg/ml',NULL,8.37,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ergometrina maleato','Comprimido','0,2 mg',NULL,1.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ergotamina tartrato + Cafeína','Comprimido','1 mg + 100 mg',NULL,2.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritromicina','Loción','2% a 4%',NULL,56.63,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritromicina (estearato)','Cápsula o Comprimido','500 mg',NULL,1.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritromicina (etilsuccinato)','Suspensión','250 mg/5 ml',NULL,13.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritropoyetina','Inyectable','10.000 UI',NULL,56.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritropoyetina','Inyectable','4000 UI',NULL,42.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eritropoyetina','Inyectable','2.000 UI ',NULL,32.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Erlotinib','Comprimido','150 mg',NULL,533.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Espiramicina','Comprimido','500 mg',NULL,7.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Espironolactona','Comprimido','100 mg',NULL,1.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Espironolactona','Comprimido','25 mg',NULL,0.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estradiol + Noretisterona acetato','Comprimido','2mg + 1mg',NULL,146.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estradiol valerianato + Norgestrel','Comprimido','2 mg + 0,5 mg',NULL,95.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estradiol valerianato + Prasterona enantato','Inyectable','4 mg + 200 mg/ml',NULL,113.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estreptomicina sulfato','Inyectable','1 g',NULL,5.13,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estreptoquinasa','Inyectable','1.500.000 UI',NULL,1074.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estrógenos conjugados','Crema vaginal','0,625 mg',NULL,116.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estrógenos conjugados','Comprimido','1,25 mg',NULL,5.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Estrógenos conjugados','Comprimido','0,625 mg',NULL,4.74,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Etambutol','Comprimido','400 mg',NULL,0.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Etamsilato','Inyectable','250 mg/2 ml',NULL,31.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Eter alifático dietilamino etanol','Solución 1 l','Según disponibilidad',NULL,614.92,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Etilefrina','Inyectable','10 mg/ml',NULL,13.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Etionamida','Comprimido','250 mg',NULL,0.73,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Etopósido','Inyectable','100 mg/5 ml',NULL,61.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Factor IX de la coagulación','Inyectable','500 UI',NULL,2150.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Factor VIII de la coagulación','Inyectable','500 UI',NULL,1938.17,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Favipiravir','Comprimido recubierto','200 mg',NULL,42.92,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fenitoína','Inyectable','50 mg/ml',NULL,12.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fenitoína','Cápsula o Comprimido','100 mg',NULL,0.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Fenobarbital','Gotas','20 mg/ml',NULL,56.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fenobarbital','Inyectable','100 mg/ml',NULL,37.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fenobarbital','Comprimido','100 mg',NULL,1.52,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fenofibrato','Cápsula o Comprimido','200 mg',NULL,4.98,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fentanilo con conservante','Inyectable','0,05 mg/ml',NULL,33.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fentanilo sin conservante','Inyectable','0,05 mg/ml',NULL,9.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fibra natural','Polvo o granulado','Según disponibilidad',NULL,3.49,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fibrinógeno humano ','Inyectable','1g',NULL,5800.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Filgrastrim','Inyectable','300 mcg/ml',NULL,103.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Finasterida','Comprimido','5 mg',NULL,2.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Fingolimod','Cápsula','0,5 mg',NULL,187.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fitomenadiona  (Vitamina K1)','Inyectable','10 mg/ml',NULL,2.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluconazol','Inyectable','200 mg',NULL,28.56,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluconazol','Comprimido o Cápsula','150 mg',NULL,2.95,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fludarabina','Inyectable','50 mg ',NULL,1260.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Flumazenil','Inyectable','0,5 mg/5 ml',NULL,131.64,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Flunarizina','Comprimido','10 mg',NULL,2.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluoresceina','Inyectable','10%',NULL,82.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluoresceina (sal sódica)','Solución oftálmica','0,25%',NULL,46.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluorouracilo','Inyectable','500 mg/10 ml',NULL,42.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Fluoruro de sodio','Gel o Pasta','Según Programa',NULL,25.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluoruro de sodio','Solución oral gotas','0,20%',NULL,19.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Fluoxetina','Cápsula o Comprimido','20 mg',NULL,0.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Flutamida','Comprimido','250 mg',NULL,3.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Formaldehido','Solución','40% p/v',NULL,22.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Furosemida','Inyectable','10 mg/ml',NULL,1.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Furosemida','Comprimido ranurado','40 mg',NULL,0.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gadodiamida','Inyectable','287 mg/ml',NULL,473.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gadopentato de dimeglumina','Inyectable','469 mg/ml',NULL,450.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gadoversetamida','Inyectable','0.5mmol / ml',NULL,450.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Gemcitabina','Inyectable','1 g',NULL,464.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gemcitabina','Inyectable','200 mg',NULL,192.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gemfibrozilo','Comprimido','600 mg',NULL,2.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gentamicina','Ungüento oftálmico','0,30%',NULL,26.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gentamicina','Solución oftálmica','0,30%',NULL,11.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gentamicina sulfato','Inyectable','20 mg',NULL,2.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gentamicina sulfato','Inyectable','80 mg',NULL,2.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Glibenclamida','Comprimido','5 mg',NULL,0.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Glicerina + carbonato de sodio','Gotas óticas','Según disponibilidad',NULL,25.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Glicerol (Glicerina bidestilada)','Solución 1 l','Según disponibilidad',NULL,106.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Glicerol (Glicerina)','Supositorio','2 g a 4 g (adulto)',NULL,2.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Glicerol (Glicerina)','Supositorio','1 g a 1,80 g (infantil)',NULL,1.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Globulina Anti-timocito','Inyectable','250 mg/5ml',NULL,2813.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Globulina Anti-timocito (conejo)','Inyectable','25 mg',NULL,0.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gluconato Cálcico (Calcio Gluconato)','Inyectable','10%',NULL,3.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Gonadotrofina coriónica','Inyectable','5.000 UI/ml',NULL,241.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Griseofulvina','Suspensión','125 mg/5 ml',NULL,23.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Griseofulvina','Comprimido','500 mg',NULL,1.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Haloperidol','Solución oral','2 mg/ml',NULL,53.44,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Haloperidol','Inyectable','5 mg/ml',NULL,27.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Haloperidol','Comprimido','5 mg',NULL,1.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Haloperidol decanoato','Inyectable','50 mg/ml',NULL,79.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Halotano','Solución','0,01% de timol',NULL,450.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Heparina de bajo peso molecular','Inyectable','Según disponibilidad',NULL,58.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Heparina sódica','Inyectable','5.000 UI/ml',NULL,44.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidralazina clorhidrato','Inyectable','20 mg/ml',NULL,70.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidralazina clorhidrato','Comprimido','25 mg',NULL,0.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroclorotiazida','Comprimido ranurado','50 mg',NULL,0.78,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroclorotiazida + Amilorida','Comprimido','50 mg + 5 mg',NULL,1.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidrocortisona acetato','Crema o Pomada','1%',NULL,11.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Hidrocortisona succinato sódico','Inyectable','250 mg',NULL,45.87,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidrocortisona succinato sódico','Inyectable','100 mg',NULL,11.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroquinona','Loción','4% o 5%',NULL,51.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroquinona','Crema a Pomada','4% o  5 %',NULL,37.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroxicloroquina sulfato','Comprimido','200 mg',NULL,6.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidróxido de aluminio y magnesio','Suspensión','01:01',NULL,12.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hidroxiurea','Cápsula','500 mg',NULL,3.34,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hierro','Inyectable','100 mg - IM o IV',NULL,34.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hierro (como bisglicina quelato)','Suspensión ','30 mg/5 mL ',NULL,69.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Hipoclorito de sodio','Solución','8%',NULL,14.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ibuprofeno','Inyectable','5 mg/ml ',NULL,34.65,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ibuprofeno','Suspensión','100 mg/5 ml',NULL,9.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ibuprofeno','Comprimido','400 mg',NULL,0.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ifosfamida','Inyectable','1 g',NULL,131.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Imatinib','Comprimido','400 mg',NULL,314.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Imatinib','Comprimido','100 mg',NULL,43.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Imipenem + Cilastatina','Inyectable','500 mg + 500 mg',NULL,68.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Imipramina clorhidrato','Comprimido','25 mg',NULL,0.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Indometacina','Supositorio','100 mg',NULL,1.68,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Indometacina','Cápsula o Comprimido','25 mg',NULL,0.26,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Inmunoglobulina anti D (RH +)','Inyectable','0,1 mg/ml a  0,2 mg/ml',NULL,830.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Inmunoglobulina humana normal','Inyectable','5 g IV',NULL,2500.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Insulina Glargina','Inyectable','100 U.I/ml',NULL,411.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Insulina Glulisina','Inyectable','100 U.I/ml',NULL,325.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Insulina recombinante humana NPH','Inyectable','100 UI/ml',NULL,125.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Insulina zinc cristalina  recombinante humana','Inyectable','100 UI/ml',NULL,95.84,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Interferon alfa 2 b recombinante','Inyectable','10.000.000 UI con diluyente (1 ml)',NULL,195.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Interferon alfa 2 b recombinante','Inyectable','3.000.000 UI con diluyente (1 ml)',NULL,90.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Interferon beta','Inyectable','0,3 mg',NULL,535.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Iodo (Yodo)','Solución hidroalcohólica','2%',NULL,86.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Iodo povidona (Yodopovidona)','Crema o Pomada','10% ( 500 g ) ',NULL,120.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Iodo povidona (Yodopovidona)','Solución','10%',NULL,81.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ipecacuana','Jarabe','7%',NULL,19.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ipratropio bromuro','Aerosol','20 mcg/dosis',NULL,138.42,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Irinotecan','Inyectable','100 mg /5 ml',NULL,480.84,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Isoniazida (INH)','Comprimido','100 mg',NULL,0.13,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Isosorbida Mononitrato','Comprimido','20 mg',NULL,2.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ivermectina','Comprimido','6 mg',NULL,10.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ivermectina','Comprimido','3 mg',NULL,8.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Kanamicina','Inyectable','1 g',NULL,16.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ketamina (Cetamina)','Inyectable','50 mg/ml',NULL,41.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ketoprofeno','Inyectable','100 mg',NULL,13.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ketorolaco','Inyectable','30 mg/ml',NULL,6.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ketotifeno','Solución oftálmica','0,25 mg/ml',NULL,118.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ketotifeno','Comprimido','1 mg',NULL,3.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Labetalol','Inyectable','20 mg',NULL,60.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lactulosa','Solución oral','65% a  67%',NULL,58.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lágrimas artificiales','Gel','0,3% o 1%',NULL,60.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lágrimas artificiales','Solución oftálmica','0,3% o 1%',NULL,21.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lamivudina','Jarabe o Solución oral','10 mg/ml',NULL,19.41,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Lamivudina','Comprimido','150 mg',NULL,0.39,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lamotrigina','Comprimido','100 mg',NULL,13.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lamotrigina','Comprimido','200 mg',NULL,11.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lamotrigina','Comprimido','50 mg',NULL,8.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lamotrigina','Comprimido','25 mg',NULL,5.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Latanoprost','Solución oftálmica','50 mcg/ml',NULL,83.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ledipasvir + Sofosbuvir','Comprimido','90 mg + 400 mg',NULL,966.65,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Leflunomida','Comprimido','100 mg',NULL,50.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Leflunomida','Comprimido','20 mg',NULL,10.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lenalidomida','Cápsula','25 mg',NULL,1683.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Lenalidomida','Cápsula','15 mg',NULL,1460.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lenalidomida','Cápsula','10 mg',NULL,973.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lenalidomida','Cápsula','5 mg',NULL,280.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Letrozol','Comprimido','2,5 mg',NULL,6.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Leucovorina','Inyectable','50 mg',NULL,47.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Leucovorina (Folinato de calcio)','Comprimido','15 mg',NULL,36.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Leuprolide','Inyectable','7,5 mg ',NULL,1774.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levodopa + Carbidopa','Comprimido','250 mg + 25 mg',NULL,3.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levofloxacina','Inyectable','500 mg',NULL,46.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levofloxacina','Comprimido','500 mg',NULL,2.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Levonorgestrel','Implante subdérmico','150 mg ',NULL,121.41,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levonorgestrel','Comprimido','1,5 mg',NULL,15.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levonorgestrel','Comprimido','0,75 mg',NULL,13.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levonorgestrel + Etinilestradiol','Comprimido','0,150 mg + 0,03 mg',NULL,5.98,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levotiroxina  sòdica','Comprimido','0,05 mg ',NULL,0.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Levotiroxina sódica','Comprimido ranurado','0,1 mg',NULL,0.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lidocaína','Gel o Jalea','2%',NULL,23.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lidocaína','Cartucho dental','2%',NULL,3.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lidocaína clorhidrato','Solución para atomización','10%',NULL,70.94,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lidocaína clorhidrato + Epinefrina','Inyectable','2% 1:200.000',NULL,18.43,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Lidocaína clorhidrato + Epinefrina','Cartucho dental','2% 1:200.000',NULL,3.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lidocaína clorhidrato sin conservante','Inyectable','2%',NULL,10.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Linezolid','Comprimido','600 mg',NULL,15.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Litio carbonato','Comprimido','300 mg',NULL,2.44,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Loperamida','Cápsula o Comprimido','2 mg',NULL,0.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lopinavir + Ritonavir','Solución oral','80 mg + 20 mg/ml',NULL,5.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Lopinavir + Ritonavir','Comprimido ','200 mg + 50 mg',NULL,3.18,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Losartán','Comprimido','50 mg',NULL,0.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mebendazol','Suspensión','100 mg/5 ml',NULL,5.95,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mebendazol','Comprimido','500 mg',NULL,2.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Mebendazol','Comprimido','100 mg',NULL,0.34,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Medroxiprogesterona acetato','Inyectable','150 mg/ml',NULL,11.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Medroxiprogesterona acetato','Inyectable','104mg/0,65 ml',NULL,9.49,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Medroxiprogesterona acetato','Comprimido','10 mg',NULL,2.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mefloquina (clorhidrato)','Comprimido','250 mg',NULL,5.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Meglumina antimoniato','Inyectable','1,5 g/5 ml',NULL,67.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Meglumina diatrizoato','Inyectable','70% o 76% (50 ml)',NULL,156.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Meglumina diatrizoato','Inyectable','70% o 76% (20 ml)',NULL,120.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Melfalán','Inyectable','500 mg',NULL,0.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Melfalán','Comprimido','2 mg',NULL,23.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Meloxicam','Comprimido','15 mg',NULL,3.03,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mercaptopurina','Comprimido ranurado','50 mg',NULL,7.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Meropenem','Inyectable','500 mg',NULL,106.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mesalazina','Supositorio','1g',NULL,36.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mesalazina','Comprimido','500 mg',NULL,8.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mesna (Mercapto etilsulfonato sódico)','Inyectable','400 mg',NULL,64.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metadona','Comprimido','5 mg',NULL,4.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metamizol (Dipirona)','Inyectable','1 g',NULL,1.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metformina','Comprimido','850 mg',NULL,1.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metformina','Comprimido','500 mg',NULL,0.68,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Metildopa (Alfametildopa)','Comprimido','500 mg',NULL,1.91,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metilfenidato','Comprimido','10 mg',NULL,16.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metilprednisolona succinato sódico','Inyectable','500 mg',NULL,113.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metoclopramida','Solución oral gotas','0,35% o 0,5%',NULL,13.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metoclopramida','Inyectable','10mg / 2ml',NULL,2.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metoclopramida','Comprimido','10 mg',NULL,0.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metotrexato','Inyectable','500 mg',NULL,132.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metotrexato','Inyectable','50 mg',NULL,61.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metotrexato','Comprimido','2,5 mg',NULL,3.52,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metronidazol','Suspensión','125 mg/5 ml',NULL,14.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Metronidazol','Suspensión','250 mg/5 ml',NULL,14.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metronidazol','Inyectable','500 mg',NULL,12.68,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metronidazol','Óvulo','500 mg',NULL,1.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Metronidazol','Comprimido','500 mg',NULL,0.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Micofenolato de mofetilo','Comprimido','500 mg',NULL,5.47,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Micronutrientes (Vit. C + Vit A + Fe + Zn + Ac. Fólico) (Chispitas nutricionales)','Polvo','Según concentración estándar',NULL,0.41,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Midazolam','Inyectable','15 mg/3 ml',NULL,20.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mifepristona','Comprimido','200 mg',NULL,122.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Milrinona','Inyectable','1 mg/ml',NULL,200.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Minociclina ','Comprimido','100 mg',NULL,6.88,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Misoprostol','Comprimido','200 mcg',NULL,7.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Misoprostol','Comprimido vaginal','25 mcg',NULL,5.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mitomicina','Inyectable','20 mg',NULL,325.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Mivacuronio','Inyectable','2 mg/ml',NULL,118.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Montelukast','Comprimido o Cápsula','10 mg',NULL,5.84,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Montelukast','Comprimido','5 mg',NULL,4.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Morfina','Cápsula o Comprimido','10 mg',NULL,2.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Morfina (con y sin conservante)','Inyectable','10 mg/ml',NULL,15.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Moxifloxacina','Comprimido','400 mg',NULL,3.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Multivitaminas','Polvo liofilizado','Según disponibilidad',NULL,50.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Multivitaminas','Jarabe','Según concentración estándar',NULL,16.56,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Multivitaminas','Comprimido','Según concentración estándar',NULL,0.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nafazolina clorhidrato','Solución oftálmica','0,10%',NULL,19.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Naloxona','Inyectable','0,4 mg/ml',NULL,63.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Naratriptan','Comprimido','2,5 mg',NULL,12.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Neostigmina','Inyectable','0,5 mg/ml',NULL,6.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nevirapina','Suspensión','10 mg/ml',NULL,20.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nevirapina','Comprimido','200 mg',NULL,0.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Niclosamida','Comprimido','500 mg',NULL,7.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nifedipino','Comprimido o Cápsula','10 mg',NULL,0.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Nifurtimox','Comprimido','120 mg',NULL,17.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nifurtimox','Comprimido','250 mg',NULL,2.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nifurtimox','Comprimido','30 mg',NULL,0.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nimodipina','Inyectable','0,2 mg/ml',NULL,172.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nimodipina','Comprimido','30 mg',NULL,0.93,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nimotuzumab','Inyectable','50 mg',NULL,68.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nistatina','Suspensión','500.000 UI/5 ml',NULL,19.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nistatina','Crema o Pomada','100.000 UI/g',NULL,10.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nistatina','Óvulo','100.000 UI',NULL,1.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nistatina','Comprimido','500.000 UI',NULL,0.61,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Nitazoxanida','Jarabe','100 mg / 5 ml',NULL,15.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitazoxanida','Comprimido','500 mg',NULL,6.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitrofural (Nitrofurazona)','Crema o Pomada','0,2% (450 g)',NULL,107.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitrofurantoína','Suspensión','25 mg/5 ml',NULL,14.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitrofurantoína','Comprimido','100 mg',NULL,1.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitroglicerina (Trinitrato de glicerol)','Inyectable','5 mg/ml',NULL,61.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Nitroprusiato de sodio','Inyectable','25 mg/ml',NULL,200.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Noradrenalina ','Inyectable','1 mg/ml',NULL,28.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Noretisterona','Comprimido','5 mg',NULL,1.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Norgestrel + Etinilestradiol','Comprimido','0,3 mg + 0,03 mg ó 0,5 mg + 0,05 mg',NULL,6.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ofloxacina','Comprimido','400 mg',NULL,0.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ofloxacina','Comprimido','200 mg',NULL,0.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oligoelementos para nutricion parenteral','Solución parenteral de gran volúmen','Según disponibilidad',NULL,45.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Omeprazol','Inyectable','40 mg/ml',NULL,14.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Omeprazol','Cápsula','20 mg',NULL,0.57,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ondansetrón','Inyectable','8 mg',NULL,15.61,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ondansetrón','Comprimido','8 mg',NULL,9.74,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oseltamivir','Cápsula','75 mg',NULL,23.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oseltamivir','Suspensión','30 mg/5 ml',NULL,22.55,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oseltamivir','Suspensión','12 mg/ml',NULL,13.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Oxaliplatino','Inyectable','100 mg',NULL,301.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oxaliplatino','Inyectable','50 mg',NULL,211.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oxido de Zinc con o sin aceite','Pasta o Pomada','Según disponibilidad',NULL,16.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oxígeno','Gas','93% - 99%',NULL,18.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Oxitocina ','Inyectable','5 UI/ml o 10 UI/ml',NULL,2.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paclitaxel','Inyectable','30 mg/5 ml',NULL,155.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paclitaxel ','Inyectable','300 mg/50 ml
',NULL,621.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paracetamol (Acetaminofeno)','Inyectable','1 gr',NULL,58.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paracetamol (Acetaminofeno)','Jarabe','120 mg/5 ml o 125 mg/5 ml',NULL,7.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paracetamol (Acetaminofeno)','Gotas','100 mg/ml',NULL,5.73,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Paracetamol (Acetaminofeno)','Supositorio','100 mg',NULL,1.76,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paracetamol (Acetaminofeno)','Comprimido','500 mg',NULL,0.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Paracetamol (Acetaminofeno)','Comprimido','100 mg',NULL,0.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pazopanib','Comprimido','200 mg',NULL,278.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pegaspargasa','Plegable Frasco Vial','750 mg/ml ',NULL,7350.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Penicilamina','Comprimido','250 mg',NULL,13.04,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pentamidina','Inyectable','300 mg',NULL,816.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pentamidina','Inyectable','200 mg',NULL,503.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Permanganato de potasio','Solución acuosa','1:10.000',NULL,6.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Permetrina','Crema o Pomada','5%',NULL,61.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Permetrina','Loción','1%',NULL,28.43,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Peróxido de Benzoílo','Loción','5%',NULL,85.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Peróxido de Benzoílo','Crema, Pomada o Gel','5%',NULL,64.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Peróxido de hidrógeno (Agua oxigenada)','Solución','2% o 3%',NULL,13.28,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pertuzumab','Inyectable','420 mg/14 ml',NULL,18792.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Petidina (Meperidina)','Inyectable','100 mg',NULL,50.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Piperacilina + Tazobactam','Inyectable ','4 g/500 mg',NULL,108.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pirantel pamoato','Suspensión','250 mg/5 ml',NULL,15.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pirantel pamoato','Comprimido','250 mg',NULL,2.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pirazinamida','Comprimido','500 mg',NULL,0.29,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Piridostigmina','Comprimido','60 mg',NULL,2.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Piridoxina clorhidrato (Vitamina B6)','Inyectable','300 mg',NULL,5.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Piridoxina clorhidrato (Vitamina B6)','Comprimido','300 mg',NULL,2.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pirimetamina','Comprimido','25 mg',NULL,0.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pralidoxima','Inyectable','1 g',NULL,2378.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Prazicuantel','Comprimido','600 mg',NULL,3.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Prednisona','Suspensión','1 mg/ml',NULL,53.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Prednisona','Comprimido ranurado','20 mg',NULL,0.92,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Prednisona','Comprimido','5 mg',NULL,0.34,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pregabalina','Comprimido o Cápsula','150 mg',NULL,14.08,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Pregabalina','Comprimido o Cápsula','75 mg',NULL,6.68,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Pregabalina','Comprimido o Cápsula','50 mg',NULL,6.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Primaquina (base)','Suspensión','15 mg/5 ml',NULL,31.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Primaquina (base)','Comprimido','15 mg',NULL,0.16,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Primaquina (base)','Comprimido','5 mg',NULL,0.12,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Progesterona ','Cápsula','200 mg',NULL,6.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Propiltiouracilo','Comprimido','50 mg',NULL,1.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Propinoxato','Inyectable','5 mg/ml',NULL,8.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Propinoxato','Comprimido','10 mg',NULL,1.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Propofol','Inyectable','10 mg/ml',NULL,41.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Propranolol','Inyectable','1 mg/ml',NULL,37.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Propranolol','Comprimido','40 mg',NULL,0.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Protamina Sulfato','Inyectable','10 mg/ml',NULL,135.52,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Proteinas para alimentación enteral (alimento)','Polvo','Según disponibilidad',NULL,85.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Proximetacaina (Proparacaina)','Solución oftálmica','0,50%',NULL,78.95,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Quetiapina','Comprimido','100 mg',NULL,9.74,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Quinina (bisulfato o sulfato)','Comprimido','300 mg',NULL,0.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Quinina (diclorhidrato)','Inyectable','600 mg',NULL,27.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Raltegravir (potasico)','Comprimido','400 mg',NULL,77.72,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ranitidina','Inyectable','50 mg',NULL,1.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Ranitidina','Comprimido','150 mg',NULL,0.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Remifentanilo','Inyectable','5 mg',NULL,130.62,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Resina de Podofilo (Podofilina)','Solución tópica','10% o 25%',NULL,35.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Resorcinol','Crema o Pomada','10%',NULL,22.67,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Retinol (Vitamina A)','Cápsula o Perla','100.000 UI',NULL,1.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Retinol (Vitamina A)','Cápsula o Perla','200.000 UI',NULL,1.08,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Retinol (Vitamina A)','Cápsula o Perla','25.000 UI',NULL,0.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Retinol (Vitamina A)','Cápsula o Perla','10.000 UI',NULL,0.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina','Suspensión','100 mg/5 ml',NULL,28.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina','Cápsula o Comprimido','300 mg',NULL,1.73,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Rifampicina','Cápsula o Comprimido','150 mg',NULL,1.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina + Isoniazida (INH)','Comprimido','300 mg + 150 mg',NULL,0.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina, Clofazimina, Dapsona','Comprimido','300 mg + 100 mg + 100 mg',NULL,22.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina, Clofazimina, Dapsona','Comprimido','300 mg + 50 mg + 50 mg',NULL,13.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina, Dapsona','Comprimido','300 mg + 50 mg',NULL,2.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rifampicina, Dapsona','Comprimido','300 mg + 100 mg',NULL,1.99,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Risperidona','Comprimido','3 mg',NULL,4.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ritodrina','Inyectable','10 mg/ml',NULL,82.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ritodrina','Comprimido','10 mg',NULL,8.24,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ritonavir','Cápsula blanda','100 mg',NULL,17.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Rituximab','Inyectable','500 mg/50 ml',NULL,10287.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rituximab','Inyectable','100 mg/10ml',NULL,6612.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rivaroxabán','Comprimido','10 mg',NULL,25.42,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rocuronio bromuro','Inyectable','10 mg/ml',NULL,79.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Rosuvastatina','Comprimido','20 mg',NULL,12.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Salbutamol','Solución para nebulización','5 mg/ml',NULL,29.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Salbutamol','Aerosol','0,1 mg/inhalación',NULL,19.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Salbutamol','Comprimido','4 mg',NULL,0.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sales de rehidratación oral (SRO) baja osmolaridad','Sobres','Según concentración estándar',NULL,1.96,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Salmeterol + Fluticasona','Aerosol','25 mcg + 125 mcg',NULL,109.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Sevoflurano (Trifluorometil etil)','Solución','250 ml',NULL,1093.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sildenafilo','Comprimido','50 mg',NULL,2.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Simeticona','Suspensión','3% o 4%',NULL,22.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Simeticona','Comprimido','100 mg',NULL,1.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sofosbuvir','Comprimido','400 mg',NULL,380.51,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solucion Acida','Solución','Según disponibilidad',NULL,120.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución Básica','Solución','Según disponibilidad',NULL,120.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa','Solución parenteral de gran volumen','50% (500 ml)',NULL,19.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa','Solución parenteral de gran volumen','5% (1.000 ml)',NULL,13.44,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa','Solución parenteral de gran volumen','10% (1.000 ml)',NULL,10.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Solución de glucosa','Solución parenteral de gran volumen','10% (500 ml)',NULL,8.87,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa','Solución parenteral de gran volumen','5% (500 ml)',NULL,8.59,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa','Inyectable','50% (20 ml)',NULL,6.76,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de glucosa ','Solución parenteral','10% (250 ml)',NULL,9.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de Manitol','Solución parenteral de gran volumen','20% (500 ml)',NULL,23.90,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución de preservación de órganos sòlidos HTK','Soluciòn','Según disponibilidad',NULL,2440.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución Fisiológica','Solución Nasal','0,9% (15 a 30 ml)',NULL,17.52,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución Fisiológica','Solución parenteral de gran volumen','0,9% (1.000 ml)',NULL,10.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución Fisiológica','Solución parenteral de gran volumen','0,9% (500 ml)',NULL,9.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución Fisiológica','Solución parenteral ','0,9% (150 ml)',NULL,7.65,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Solución Fisiológica','Solución parenteral','0,9% (100 ml)',NULL,7.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución glucosada clorurada','Solución parenteral de gran volumen','1.000 ml',NULL,10.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución glucosada clorurada','Solución parenteral de gran volumen','500 ml',NULL,7.05,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solucion para dialisis intraperitoneal (de acuerdo a composicion apropiada)','Solución parenteral ','Según disponibilidad',NULL,59.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución para dialisis peritoneal I','Solución parenteral de gran volumen','1.000 ml',NULL,14.42,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución para dialisis peritoneal II','Solución parenteral de gran volumen','1.000 ml',NULL,18.43,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución ringer lactato','Solución parenteral de gran volumen','1.000 ml',NULL,11.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución ringer lactato','Solución parenteral de gran volumen','500 ml',NULL,8.01,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución ringer normal','Solución parenteral de gran volumen','1.000 ml',NULL,11.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Solución ringer normal','Solución parenteral de gran volumen','500 ml',NULL,8.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Somatropina ','Inyectable','4UI (1,33 mg)',NULL,0.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sucralfato','Suspensión','1g/5 ml',NULL,68.30,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suero Antiescorpionico','Inyectable','Según disponibilidad',NULL,60.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suero Antilatrodectus','Inyectable','Según disponibilidad',NULL,60.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suero Antiofídico Botrópico Crotàlico','Inyectable','Según disponibilidad',NULL,135.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suero Antiofídico Botrópico Laquésico','Inyectable','Según disponibilidad',NULL,135.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suero Antirràbico (heterólogo)','Inyectable','Según disponibilidad',NULL,90.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfadiazina de plata','Crema o Pomada','1%',NULL,48.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfadoxina + Pirimetamina','Comprimido','500 mg + 25 mg',NULL,0.32,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato de Bario','Polvo para enema','Según disponibilidad',NULL,321.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Sulfato de Bario','Suspensión','Según disponibilidad',NULL,235.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato de Magnesio','Inyectable','10%',NULL,5.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato de Magnesio','Granulado','20 g a 30 g',NULL,2.08,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato ferroso','Solución oral','125 mg/ml',NULL,12.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato ferroso','Comprimido','200 mg',NULL,0.37,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato ferroso + Ac. Fólico + Vitamina C','Solución oral','125 mg + 0,25 mg + 30 mg',NULL,7.35,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Sulfato ferroso + Ac. Fólico + Vitamina C','Comprimido','200 mg + 0,5 mg + 150 mg',NULL,0.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Surfactante pulmonar','Inyectable','25 a 35 mg/ml',NULL,1444.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Suxametonio (Succinil colina)','Inyectable','500 mg',NULL,64.08,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tacrolimus','Cápsula','1 mg',NULL,10.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Talidomida','Comprimido','100 mg',NULL,16.13,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tamoxifeno','Comprimido','20 mg',NULL,2.97,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Temozolomida','Cápsula','250 mg',NULL,754.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Temozolomida','Cápsula','100 mg',NULL,222.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Temozolomida','Cápsula','20 mg',NULL,68.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tenecteplasa  ','Polvo para Inyectable','50 mg',NULL,6626.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tenofovir disoproxilo','Comprimido','245 mg (Equiv. a 300  mg como fumarato)',NULL,2.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tenofovir disoproxilo + Efavirenz + Lamivudina','Comprimido','300 mg + 600 mg + 300 mg ',NULL,3.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Teofilina','Comprimido','300 mg',NULL,4.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Terbinafina','Comprimido','250 mg',NULL,12.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Terlipresina','Inyectable','1 mg',NULL,561.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Testosterona undecanoato','Inyectable','1.000 mg',NULL,1220.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tetraciclina','Cápsula o Comprimido','500 mg',NULL,0.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiabendazol','Suspensión','500 mg/5 ml',NULL,24.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiabendazol','Crema o Pomada','5%',NULL,15.37,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiabendazol','Comprimido','500 mg',NULL,2.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiamazol (Metimazol) ','Comprimido','20 mg',NULL,2.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiamina (Vitamina B 1)','Inyectable','100 mg/ml',NULL,3.04,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tiamina (Vitamina B 1)','Comprimido','300 mg',NULL,1.09,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Timolol maleato','Solución oftálmica','0,50%',NULL,24.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Tiopental sódico','Inyectable','1 g',NULL,36.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tioridazina','Suspensión','100 mg/5 ml',NULL,33.71,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tioridazina','Comprimido','100 mg',NULL,4.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tocoferol (Vitamina E)','Cápsula blanda','1.000 UI',NULL,1.64,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tolnaftato','Solución','1%',NULL,23.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Toxoide tetánico adsorbido','Inyectable','120 UI/ml',NULL,20.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tramadol','Comprimido','50 mg',NULL,2.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tramadol ','Solución para gotas orales','100 mg/ml',NULL,55.19,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tramadol ','Inyectable','100 mg/2 ml',NULL,9.10,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Trastuzumab','Inyectable','600 mg',NULL,15835.36,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Trastuzumab','Inyectable','440 mg',NULL,5500.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Triclabendazol','Comprimido','250 mg',NULL,343.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Triptorelina','Inyectable','22,5 mg',NULL,9380.20,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Triptorelina','Inyectable','11,25 mg',NULL,4759.18,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Trolamina ','Emulsión dermica','0,67%',NULL,183.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Tropicamida','Solución oftálmica','1%',NULL,82.45,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Ungüento dérmico eucalipto mentol','Ungüento o crema','Según disponibilidad',NULL,6.86,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antiamarílica','Inyectable','Norma PAI (20 dosis)',NULL,10.14,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antiamarílica','Inyectable','Norma PAI (10 dosis)',NULL,9.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antiamarílica','Inyectable','Norma PAI (5 dosis)',NULL,8.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Vacuna antihepatitis B','Inyectable','Norma PAI',NULL,2.96,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antineumococo  (13 valente)','Inyectable','Norma PAI (Unidosis)',NULL,63.46,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antipoliomielítica bivalente','Solución oral','Norma PAI ',NULL,1.13,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna antipoliomielítica inactivada','Inyectable','Norma PAI',NULL,17.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna Antirotavírica','Solución oral','Norma PAI Multidosis',NULL,66.53,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna Antirotavírica','Solución oral','Norma PAI (Unidosis)',NULL,58.93,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna Antirrábica','Inyectable','1 UI/ml',NULL,70.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna Antirrábica de uso Humano (Cultivo Celular)','Inyectable','2,5 U.I./0,5 ml',NULL,219.80,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna BCG','Inyectable','Norma PAI',NULL,1.31,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna contra COVID-19','Inyectable','Norma PAI',NULL,0.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Vacuna contra Influenza (Adulto)','Inyectable','Norma PAI (10 dosis)',NULL,25.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna contra Influenza (Pediátrica)','Inyectable','Norma PAI (10 dosis)',NULL,12.69,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna cuadrivalente recombinante contra el Virus del Papiloma Humano','Inyectable','Norma PAI',NULL,40.79,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna doble dT (difteria, Tétanos)','Inyectable','Norma PAI',NULL,1.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna pentavalente (DPT + Hep. B + H. Influenzae B)','Inyectable','Norma PAI',NULL,19.04,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna SR (Sarampión, Rubeola)','Inyectable','Norma PAI',NULL,20.40,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna SRP (Sarampión, Rubeola; Paperas)','Inyectable','Norma PAI (Unidosis)',NULL,21.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna SRP (Sarampión, Rubeola; Paperas)','Inyectable','Norma PAI Multidosis',NULL,11.66,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vacuna Triple DPT (Difteria, Pertusis, Tetanos)','Inyectable','Norma PAI',NULL,2.03,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Valganciclovir','Comprimido','450 mg',NULL,300.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Vancomicina','Inyectable','500 mg',NULL,25.89,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vaselina liquida','Solución 1 l','Según disponibilidad ',NULL,55.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vaselina sólida','Pasta 1 kg','Según disponibilidad',NULL,60.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Verapamilo','Inyectable','2,5 mg/ml',NULL,28.11,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Verapamilo','Comprimido','40 mg',NULL,0.61,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Verapamilo','Comprimido','80 mg',NULL,0.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vinblastina','Inyectable','10 mg',NULL,310.50,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vincristina','Inyectable','1 mg/ml',NULL,64.93,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Vinorelbina','Inyectable','50 mg',NULL,855.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Violeta de genciana (Cloruro de metilrosanilina)','Solución','1%',NULL,2.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO providencia.productos (medicamento,forma_farmaceutica,concentracion,imagen,precio,costo,stock,activo,categoria_id,deleted_at,created_at,updated_at) VALUES
	 ('Voriconazol','Polvo para inyectable','200 mg',NULL,600.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Warfarina','Comprimido ranurado','5 mg',NULL,0.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Zidovudina','Inyectable','10 mg/ml',NULL,88.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Zidovudina','Suspensión oral','10 mg/ml',NULL,42.07,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Zidovudina + Lamivudina','Comprimido','300 mg + 150 mg',NULL,1.48,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Zinc (como sulfato)','Jarabe','20 mg/5 ml ',NULL,15.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('Zinc (como sulfato)','Comprimido','20 mg',NULL,0.65,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
